Setup mobile version
yosefHesham/porftolio pull request #1
Opened 2022-03-17 12:50 UTC by yosefHesham

Changes:

- created the toolbar with title and menu and layout them using flex
- created headline contents and layout them properly
- used the proper colors and fonts
- installing linters
- updated readme and mit

2022-03-17 14:59 UTC, OLIPLICHE requested changes
Hi 👋 , 

Good job so far!
There are some issues that you still need to work on to get your project approved, but you are almost there!

![image](https://user-images.githubusercontent.com/63972670/158831696-61343f65-0c27-403c-9227-466528de8f06.png)

## Highlights Good Points: 👍
 - [ ] Linter result is green ✔️
- [ ]  Commit messages are meaningful✔️
 - [ ] node_modules folder is in the .gitignore file and not in the repo✔️
- [ ] Pull Request have a short summary describing introduced changes in more detail✔️

## Required Changes ♻️

- CHECK THE COMMENTS UNDER THE REVIEW⬇..

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-17 14:59 UTC, OLIPLICHE commented on README.md
> +- thats it, you are good to go :)
- [x] kindly remove this `:)` to make your ReadMe more clean

2022-03-17 14:59 UTC, OLIPLICHE commented on index.html
> +              <h1>Welcome</h1>
- [x] Please this element is supposed to be the logo, Kindly use an `<a>` tag instead of a header.
   You should only use the `<h1>` header in the title of your website. Kindly use the [Semantic HTML](https://www.w3docs.com/learn-html/semantic-elements-in-html5.html)! to learn more. 💯

2022-03-17 14:59 UTC, OLIPLICHE commented on index.html
> +            <a href="#"> <img src="assets/images/hamburger.svg" alt="" /> </a>
- [ ]  Please make sure that the hamburger button is inside a <nav> tag 👍

2022-03-17 14:59 UTC, OLIPLICHE commented on index.html
> +    <header class="head-toolbar">
- [x] Please make sure that the content is aligned with flexbox 👍

2022-03-17 14:59 UTC, OLIPLICHE commented on index.html
> +    <header class="head-toolbar">
- [x] Please make sure the section has the margins (top, bottom, left, right) defined in the design.

![r2](https://user-images.githubusercontent.com/63972670/158826428-896fa1d6-a948-4008-930e-9d3a532b631e.JPG)

![r3](https://user-images.githubusercontent.com/63972670/158827307-efdc1e9a-9290-42ff-9ea6-b80e35dbdf0f.png)

2022-03-17 14:59 UTC, OLIPLICHE commented on index.html
> +    <section class="headline">
- [ ] Please make sure the content is aligned with flexbox

2022-03-17 14:59 UTC, OLIPLICHE commented on index.html
> +        </ul>
- [ ] Please make sure the section has the margins (top, bottom, left, right) defined in the design

![r5](https://user-images.githubusercontent.com/63972670/158830136-5e909af3-7d1b-47a7-b461-c47ca61751ac.JPG)

![r4](https://user-images.githubusercontent.com/63972670/158830825-bcde0d63-bc40-4044-af1c-7b5df5225c94.JPG)

2022-03-17 16:25 UTC, yosefHesham commented on index.html
> +            <a href="#"> <img src="assets/images/hamburger.svg" alt="" /> </a>
@OLIPLICHE i think its already inside the tag?

2022-03-17 16:29 UTC, yosefHesham commented on index.html
> +              <h1>Welcome</h1>
oh my bad, thanks alot

2022-03-18 05:48 UTC, yosefHesham commented on index.html
> +    <header class="head-toolbar">
it`s already aligned in the ul

2022-03-18 08:34 UTC, Mre55 approved these changes
**Hi @yosefHesham,**

# Status: APPROVED  🎉 🎊 

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚀: 
Congratulations! 🎉 

![Alt Text](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-18 08:41 UTC, merged